import type { ModuleConfig } from './types'

/**
 * Module 1 — Fire & Explosion Response (PRD 5.1).
 *
 * Built entirely from A-Frame primitives, no GLTF (Decision 2 in the README):
 * removes the asset pipeline and the PRD 12 "3D assets too heavy" risk.
 * Everything sits on the Hiro marker anchor at the origin, y up, within ~2 units.
 */
export const moduleFire: ModuleConfig = {
  id: 'fire',
  nameKey: 'modules.fire.name',
  descKey: 'modules.fire.desc',
  briefKey: 'modules.fire.brief',
  debriefKey: 'modules.fire.debrief',
  accent: '#f97316',
  steps: [
    // Step 1 - Hazard Identification
    {
      id: 'fire-1',
      titleKey: 'modules.fire.s1.title',
      promptKey: 'modules.fire.s1.prompt',
      audio: 'fire-1.mp3',
      correctIds: ['flame'],
      wrongFeedbackKey: 'modules.fire.s1.wrong',
      successKey: 'modules.fire.s1.ok',
      entities: [
        // The electrical panel that is on fire.
        {
          id: 'panel',
          kind: 'box',
          position: [0, 0.35, -0.3],
          width: 0.5,
          height: 0.7,
          depth: 0.15,
          color: '#475569',
          label: 'PANEL',
          labelColor: '#e2e8f0',
        },
        {
          id: 'flame',
          kind: 'cone',
          position: [0, 0.85, -0.3],
          radius: 0.22,
          height: 0.5,
          color: '#f97316',
          opacity: 0.95,
          tappable: true,
          animation:
            'property: scale; from: 1 0.85 1; to: 1.15 1.25 1.15; dir: alternate; loop: true; dur: 420; easing: easeInOutSine',
        },
        {
          id: 'flame-core',
          kind: 'cone',
          position: [0, 0.78, -0.3],
          radius: 0.13,
          height: 0.34,
          color: '#fde047',
          opacity: 0.9,
          animation:
            'property: scale; from: 1 1 1; to: 1.2 1.35 1.2; dir: alternate; loop: true; dur: 300; easing: easeInOutSine',
        },
        // Decoys - tapping these is a wrong answer.
        {
          id: 'crate',
          kind: 'box',
          position: [-0.75, 0.18, 0.2],
          width: 0.36,
          height: 0.36,
          depth: 0.36,
          color: '#a16207',
          label: 'CRATE',
          tappable: true,
        },
        {
          id: 'cooler',
          kind: 'cylinder',
          position: [0.75, 0.25, 0.2],
          radius: 0.16,
          height: 0.5,
          color: '#0ea5e9',
          label: 'WATER',
          tappable: true,
        },
      ],
    },

    // Step 2 - Extinguisher Selection (correct = CO2, because it is an electrical fire)
    {
      id: 'fire-2',
      titleKey: 'modules.fire.s2.title',
      promptKey: 'modules.fire.s2.prompt',
      audio: 'fire-2.mp3',
      correctIds: ['ext-co2'],
      wrongFeedbackKey: 'modules.fire.s2.wrong',
      successKey: 'modules.fire.s2.ok',
      entities: [
        {
          id: 'panel-b',
          kind: 'box',
          position: [0, 0.35, -0.6],
          width: 0.5,
          height: 0.7,
          depth: 0.15,
          color: '#475569',
        },
        {
          id: 'flame-b',
          kind: 'cone',
          position: [0, 0.85, -0.6],
          radius: 0.2,
          height: 0.45,
          color: '#f97316',
          opacity: 0.9,
          animation:
            'property: scale; from: 1 0.9 1; to: 1.1 1.2 1.1; dir: alternate; loop: true; dur: 420',
        },
        {
          id: 'ext-co2',
          kind: 'cylinder',
          position: [-0.6, 0.3, 0.35],
          radius: 0.13,
          height: 0.6,
          color: '#111827',
          label: 'CO2',
          labelColor: '#ffffff',
          tappable: true,
        },
        {
          id: 'ext-foam',
          kind: 'cylinder',
          position: [0, 0.3, 0.35],
          radius: 0.13,
          height: 0.6,
          color: '#fbbf24',
          label: 'FOAM',
          labelColor: '#111827',
          tappable: true,
        },
        {
          id: 'ext-water',
          kind: 'cylinder',
          position: [0.6, 0.3, 0.35],
          radius: 0.13,
          height: 0.6,
          color: '#dc2626',
          label: 'WATER',
          labelColor: '#ffffff',
          tappable: true,
        },
      ],
    },

    // Step 3 - Exit Route (one blocked, one clear)
    {
      id: 'fire-3',
      titleKey: 'modules.fire.s3.title',
      promptKey: 'modules.fire.s3.prompt',
      audio: 'fire-3.mp3',
      correctIds: ['exit-clear'],
      wrongFeedbackKey: 'modules.fire.s3.wrong',
      successKey: 'modules.fire.s3.ok',
      entities: [
        // Clear route - green arrows leading left.
        {
          id: 'arrow-1',
          kind: 'cone',
          position: [-0.35, 0.08, 0.35],
          rotation: [0, 0, 90],
          radius: 0.09,
          height: 0.22,
          color: '#22c55e',
        },
        {
          id: 'arrow-2',
          kind: 'cone',
          position: [-0.7, 0.08, 0.35],
          rotation: [0, 0, 90],
          radius: 0.09,
          height: 0.22,
          color: '#22c55e',
        },
        {
          id: 'exit-clear',
          kind: 'plane',
          position: [-1.05, 0.4, 0.35],
          rotation: [0, 90, 0],
          width: 0.5,
          height: 0.3,
          color: '#16a34a',
          label: 'EXIT',
          labelColor: '#ffffff',
          tappable: true,
        },
        // Blocked route - red barrier and debris to the right.
        {
          id: 'debris',
          kind: 'box',
          position: [0.7, 0.15, 0.35],
          width: 0.45,
          height: 0.3,
          depth: 0.45,
          color: '#7f1d1d',
          label: 'BLOCKED',
          labelColor: '#fecaca',
        },
        {
          id: 'exit-blocked',
          kind: 'plane',
          position: [1.05, 0.4, 0.35],
          rotation: [0, -90, 0],
          width: 0.5,
          height: 0.3,
          color: '#16a34a',
          label: 'EXIT',
          labelColor: '#ffffff',
          tappable: true,
        },
      ],
    },

    // Step 4 - Evacuation Headcount (ordered checklist)
    {
      id: 'fire-4',
      titleKey: 'modules.fire.s4.title',
      promptKey: 'modules.fire.s4.prompt',
      audio: 'fire-4.mp3',
      correctIds: ['chk-1', 'chk-2', 'chk-3'],
      requireAll: true,
      ordered: true,
      wrongFeedbackKey: 'modules.fire.s4.wrong',
      successKey: 'modules.fire.s4.ok',
      entities: [
        {
          id: 'chk-1',
          kind: 'plane',
          position: [0, 0.85, -0.2],
          width: 1.1,
          height: 0.24,
          color: '#1e293b',
          label: '1 ASSEMBLY POINT',
          labelColor: '#f8fafc',
          tappable: true,
        },
        {
          id: 'chk-2',
          kind: 'plane',
          position: [0, 0.55, -0.2],
          width: 1.1,
          height: 0.24,
          color: '#1e293b',
          label: '2 COUNT WORKERS',
          labelColor: '#f8fafc',
          tappable: true,
        },
        {
          id: 'chk-3',
          kind: 'plane',
          position: [0, 0.25, -0.2],
          width: 1.1,
          height: 0.24,
          color: '#1e293b',
          label: '3 REPORT MISSING',
          labelColor: '#f8fafc',
          tappable: true,
        },
      ],
    },

    // Step 5 - All-Clear Protocol
    {
      id: 'fire-5',
      titleKey: 'modules.fire.s5.title',
      promptKey: 'modules.fire.s5.prompt',
      audio: 'fire-5.mp3',
      correctIds: ['all-clear'],
      wrongFeedbackKey: 'modules.fire.s5.wrong',
      successKey: 'modules.fire.s5.ok',
      entities: [
        {
          id: 'all-clear',
          kind: 'plane',
          position: [0, 0.5, -0.1],
          width: 1.0,
          height: 0.4,
          color: '#16a34a',
          label: 'ALL CLEAR',
          labelColor: '#ffffff',
          tappable: true,
          animation:
            'property: scale; from: 1 1 1; to: 1.06 1.06 1; dir: alternate; loop: true; dur: 700',
        },
        {
          id: 'supervisor',
          kind: 'sphere',
          position: [-0.8, 0.2, 0.3],
          radius: 0.13,
          color: '#eab308',
          label: 'RADIO',
          labelColor: '#fef9c3',
          tappable: true,
        },
      ],
    },
  ],
}
